// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/template/template.proto

package eopenio_micro_srv_template

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Template service

type TemplateService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Template_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Template_PingPongService, error)
}

type templateService struct {
	c    client.Client
	name string
}

func NewTemplateService(name string, c client.Client) TemplateService {
	return &templateService{
		c:    c,
		name: name,
	}
}

func (c *templateService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Template.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templateService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Template_StreamService, error) {
	req := c.c.NewRequest(c.name, "Template.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &templateServiceStream{stream}, nil
}

type Template_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type templateServiceStream struct {
	stream client.Stream
}

func (x *templateServiceStream) Close() error {
	return x.stream.Close()
}

func (x *templateServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *templateServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *templateServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *templateServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *templateService) PingPong(ctx context.Context, opts ...client.CallOption) (Template_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Template.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &templateServicePingPong{stream}, nil
}

type Template_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type templateServicePingPong struct {
	stream client.Stream
}

func (x *templateServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *templateServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *templateServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *templateServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *templateServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *templateServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Template service

type TemplateHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Template_StreamStream) error
	PingPong(context.Context, Template_PingPongStream) error
}

func RegisterTemplateHandler(s server.Server, hdlr TemplateHandler, opts ...server.HandlerOption) error {
	type template interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Template struct {
		template
	}
	h := &templateHandler{hdlr}
	return s.Handle(s.NewHandler(&Template{h}, opts...))
}

type templateHandler struct {
	TemplateHandler
}

func (h *templateHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.TemplateHandler.Call(ctx, in, out)
}

func (h *templateHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.TemplateHandler.Stream(ctx, m, &templateStreamStream{stream})
}

type Template_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type templateStreamStream struct {
	stream server.Stream
}

func (x *templateStreamStream) Close() error {
	return x.stream.Close()
}

func (x *templateStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *templateStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *templateStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *templateStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *templateHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.TemplateHandler.PingPong(ctx, &templatePingPongStream{stream})
}

type Template_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type templatePingPongStream struct {
	stream server.Stream
}

func (x *templatePingPongStream) Close() error {
	return x.stream.Close()
}

func (x *templatePingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *templatePingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *templatePingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *templatePingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *templatePingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
